<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-IO7O6G3K" failures="1" tests="2" name="Default test" time="2.996" errors="0" timestamp="2025-02-24T08:39:18 IST">
  <testcase classname="test.AddToCartTest" name="verifyUserIsAbleToRemoveProductFromCart" time="0.008"/>
  <testcase classname="test.AddToCartTest" name="verifyUserIsAbleToRemoveProductFromCart" time="2.748">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because &amp;quot;test.Listeners.test&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because "test.Listeners.test" is null
at test.Listeners.onTestSuccess(Listeners.java:21)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:119)
at org.testng.internal.invokers.TestInvoker.runTestResultListener(TestInvoker.java:285)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:774)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyUserIsAbleToRemoveProductFromCart -->
  <testcase classname="test.AddToCartTest" name="verifyIfUserIsAbletoRemoveAddedProductToCartFromHomePage" time="0.0">
    <ignored/>
  </testcase> <!-- verifyIfUserIsAbletoRemoveAddedProductToCartFromHomePage -->
  <testcase classname="test.AddToCartTest" name="verifyOnCLickingAddToCartRemoveOptionIsDisplayed" time="0.0">
    <ignored/>
  </testcase> <!-- verifyOnCLickingAddToCartRemoveOptionIsDisplayed -->
  <testcase classname="test.AddToCartTest" name="verifyIfCorrectProuctIsAddedToCart" time="0.0">
    <ignored/>
  </testcase> <!-- verifyIfCorrectProuctIsAddedToCart -->
  <testcase classname="test.AddToCartTest" name="verfiyIfUserIsAbleProductToCart" time="0.0">
    <ignored/>
  </testcase> <!-- verfiyIfUserIsAbleProductToCart -->
</testsuite> <!-- Default test -->
